/* File storing the details of each advancement */
const advancementDetails: AdvancementDetailsType = {
    story: {
        root: { title: "Minecraft", desc: "The heart and story of the game", icon: { type: "block", name: "grass_block", ench: false }, type: "normal", criteria: ["crafting_table"] },
        mine_stone: { title: "Stone Age", desc: "Mine stone with your new pickaxe", icon: { type: "item", name: "wooden_pickaxe", ench: false }, type: "normal", criteria: ["get_stone"] },
        upgrade_tools: { title: "Getting an Upgrade", desc: "Construct a better pickaxe", icon: { type: "item", name: "stone_pickaxe", ench: false }, type: "normal", criteria: ["stone_pickaxe"] },
        smelt_iron: { title: "Acquire Hardware", desc: "Smelt an iron ingot", icon: { type: "item", name: "iron_ingot", ench: false }, type: "normal", criteria: ["iron"] },
        obtain_armor: { title: "Suit Up", desc: "Protect yourself with a piece of iron armor", icon: { type: "item", name: "iron_chestplate", ench: false }, type: "normal", criteria: ["iron_boots", "iron_chestplate", "iron_helmet", "iron_leggings"] },
        lava_bucket: { title: "Hot Stuff", desc: "Fill a bucket with lava", icon: { type: "item", name: "lava_bucket", ench: false }, type: "normal", criteria: ["lava_bucket"] },
        iron_tools: { title: "Isn't It Iron Pick", desc: "Upgrade your pickaxe", icon: { type: "item", name: "iron_pickaxe", ench: false }, type: "normal", criteria: ["iron_pickaxe"] },
        deflect_arrow: { title: "Not Today, Thank You", desc: "Deflect a projectile with a shield", icon: { type: "item", name: "shield", ench: false }, type: "normal", criteria: ["deflected_projectile"] },
        form_obsidian: { title: "Ice Bucket Challenge", desc: "Obtain a block of obsidian", icon: { type: "block", name: "obsidian", ench: false }, type: "normal", criteria: ["obsidian"] },
        mine_diamond: { title: "Diamonds!", desc: "Acquire diamonds", icon: { type: "item", name: "diamond", ench: false }, type: "normal", criteria: ["diamond"] },
        enter_the_nether: { title: "We Need to Go Deeper", desc: "Build, light and enter a Nether Portal", icon: { type: "item", name: "flint_and_steel", ench: false }, type: "normal", criteria: ["entered_nether"] },
        shiny_gear: { title: "Cover Me with Diamonds", desc: "Diamond armor saves lives", icon: { type: "item", name: "diamond_chestplate", ench: false }, type: "normal", criteria: ["diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_leggings"] },
        enchant_item: { title: "Enchanter", desc: "Enchant an item at an Enchanting Table", icon: { type: "item", name: "enchanted_book", ench: true }, type: "normal", criteria: ["enchanted_item"] },
        cure_zombie_villager: { title: "Zombie Doctor", desc: "Weaken and then cure a Zombie Villager", icon: { type: "item", name: "golden_apple", ench: false }, type: "goal", criteria: ["cured_zombie"] },
        follow_ender_eye: { title: "Eye Spy", desc: "Follow an Eye of Ender", icon: { type: "item", name: "ender_eye", ench: false }, type: "normal", criteria: ["in_stronghold"] },
        enter_the_end: { title: "The End?", desc: "Enter the End Portal", icon: { type: "block", name: "end_stone", ench: false }, type: "normal", criteria: ["entered_end"] },
    },
    nether: {
        root: { title: "Nether", desc: "Bring summer clothes", icon: { type: "block", name: "red_nether_bricks", ench: false }, type: "normal", criteria: ["entered_nether"] },
        return_to_sender: { title: "Return to Sender", desc: "Destroy a Ghast with a fireball", icon: { type: "item", name: "fire_charge", ench: false }, type: "normal", criteria: ["killed_ghast"] },
        find_bastion: { title: "Those Were the Days", desc: "Enter a Bastion Remnant", icon: { type: "block", name: "polished_blackstone_bricks", ench: false }, type: "normal", criteria: ["bastion"] },
        obtain_ancient_debris: { title: "Hidden in the Depths", desc: "Obtain Ancient Debris", icon: { type: "block", name: "ancient_debris", ench: false }, type: "normal", criteria: ["ancient_debris"] },
        fast_travel: { title: "Subspace Bubble", desc: "Use the Nether to travel 7 km in the Overworld", icon: { type: "item", name: "map", ench: false }, type: "challenge", criteria: ["travelled"] },
        find_fortress: { title: "A Terrible Fortress", desc: "Break your way into a Nether Fortress", icon: { type: "block", name: "nether_bricks", ench: false }, type: "normal", criteria: ["fortress"] },
        obtain_crying_obsidian: { title: "Who is Cutting Onions?", desc: "Obtain Crying Obsidian", icon: { type: "block", name: "crying_obsidian", ench: false }, type: "normal", criteria: ["crying_obsidian"] },
        distract_piglin: { title: "Oh Shiny", desc: "Distract Piglins with gold", icon: { type: "item", name: "gold_ingot", ench: false }, type: "normal", criteria: ["distract_piglin", "distract_piglin_directly"] },
        ride_strider: { title: "This Boat Has Legs", desc: "Ride a Strider with a Warped Fungus on a Stick", icon: { type: "item", name: "warped_fungus_on_a_stick", ench: false }, type: "normal", criteria: ["used_warped_fungus_on_a_stick"] },
        uneasy_alliance: { title: "Uneasy Alliance", desc: "Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it", icon: { type: "item", name: "ghast_tear", ench: false }, type: "challenge", criteria: ["killed_ghast"] },
        loot_bastion: { title: "War Pigs", desc: "Loot a chest in a Bastion Remnant", icon: { type: "block", name: "chest", ench: false, custom: true }, type: "normal", criteria: ["loot_bastion_bridge", "loot_bastion_hoglin_stable", "loot_bastion_other", "loot_bastion_treasure"] },
        use_lodestone: { title: "Country Lode, Take Me Home", desc: "Use a compass on a Lodestone", icon: { type: "block", name: "lodestone", ench: false }, type: "normal", criteria: ["use_lodestone"] },
        netherite_armor: { title: "Cover Me in Debris", desc: "Get a full suit of Netherite armor", icon: { type: "item", name: "netherite_chestplate", ench: false }, type: "challenge", criteria: ["netherite_armor"] },
        get_wither_skull: { title: "Spooky Scary Skeleton", desc: "Obtain a Wither Skeleton's skull", icon: { type: "block", name: "wither_skeleton_skull", ench: false, custom: true }, type: "normal", criteria: ["wither_skull"] },
        obtain_blaze_rod: { title: "Into Fire", desc: "Relieve a Blaze of its rod", icon: { type: "item", name: "blaze_rod", ench: false }, type: "normal", criteria: ["blaze_rod"] },
        charge_respawn_anchor: { title: 'Not Quite "Nine" Lives', desc: "Charge a Respawn Anchor to the maximum", icon: { type: "block", name: "respawn_anchor_0", ench: false }, type: "normal", criteria: ["charge_respawn_anchor"] },
        ride_strider_in_overworld_lava: { title: "Feels like home", desc: "Take a Strider for a loooong ride on a lava lake in the Overworld", icon: { type: "item", name: "warped_fungus_on_a_stick", ench: false }, type: "challenge", criteria: ["ride_entity_distance"] },
        explore_nether: {
            title: "Hot Tourist Destinations",
            desc: "Explore all Nether biomes",
            icon: { type: "item", name: "netherite_boots", ench: false },
            type: "challenge",
            criteria: ["minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:warped_forest"],
        },
        summon_wither: { title: "Withering Heights", desc: "Summon the Wither", icon: { type: "item", name: "nether_star", ench: true }, type: "normal", criteria: ["summoned"] },
        brew_potion: { title: "Local Brewery", desc: "Brew a potion", icon: { type: "item", name: "uncraftable_potion", ench: false }, type: "normal", criteria: ["potion"] },
        create_beacon: { title: "Bring Home the Beacon", desc: "Construct and place a beacon", icon: { type: "block", name: "beacon", ench: false }, type: "normal", criteria: ["beacon"] },
        all_potions: { title: "A Furious Cocktail", desc: "Have every potion effect applied at the same time", icon: { type: "item", name: "milk_bucket", ench: false }, type: "challenge", criteria: ["all_effects"] },
        create_full_beacon: { title: "Beaconator", desc: "Bring a beacon to full power", icon: { type: "block", name: "beacon", ench: false }, type: "goal", criteria: ["beacon"] },
        all_effects: { title: "How Did We Get Here?", desc: "Have every effect applied at the same time", icon: { type: "item", name: "bucket", ench: false }, type: "challenge", criteria: ["all_effects"] },
    },
    end: {
        root: { title: "The End", desc: "Or the beginning?", icon: { type: "block", name: "end_stone", ench: false }, type: "normal", criteria: ["entered_end"] },
        kill_dragon: { title: "Free the End", desc: "Good luck", icon: { type: "item", name: "dragon_head", ench: false, custom: true }, type: "normal", criteria: ["killed_dragon"] },
        dragon_egg: { title: "The Next Generation", desc: "Hold the Dragon Egg", icon: { type: "block", name: "dragon_egg", ench: false }, type: "goal", criteria: ["dragon_egg"] },
        enter_end_gateway: { title: "Remote Getaway", desc: "Escape the island", icon: { type: "item", name: "ender_pearl", ench: false }, type: "normal", criteria: ["entered_end_gateway"] },
        respawn_dragon: { title: "The End... Again...", desc: "Respawn the Ender Dragon", icon: { type: "item", name: "end_crystal", ench: true }, type: "goal", criteria: ["summoned_dragon"] },
        dragon_breath: { title: "You Need a Mint", desc: "Collect dragon's breath in a glass bottle", icon: { type: "item", name: "dragon_breath", ench: false }, type: "goal", criteria: ["dragon_breath"] },
        find_end_city: { title: "The City at the End of the Game", desc: "Go on in, what could happen?", icon: { type: "block", name: "purpur_block", ench: false }, type: "normal", criteria: ["in_city"] },
        elytra: { title: "Sky's the Limit", desc: "Find elytra", icon: { type: "item", name: "elytra", ench: false }, type: "normal", criteria: ["elytra"] },
        levitate: { title: "Great View From Up Here", desc: "Levitate up 50 blocks from the attacks of a Shulker", icon: { type: "item", name: "shulker_shell", ench: false }, type: "challenge", criteria: ["levitated"] },
    },
    adventure: {
        root: { title: "Adventure", desc: "Adventure, exploration and combat", icon: { type: "item", name: "map", ench: false }, type: "normal", criteria: ["killed_by_something", "killed_something"] },
        voluntary_exile: { title: "Voluntary Exile", desc: "Kill a raid captain.\nMaybe consider staying away from villages for the time being...", icon: { type: "block", name: "ominous_banner", ench: false }, type: "normal", criteria: ["voluntary_exile"] },
        spyglass_at_parrot: { title: "Is It a Bird?", desc: "Look at a parrot through a spyglass", icon: { type: "item", name: "spyglass", ench: false }, type: "normal", criteria: ["spyglass_at_parrot"] },
        kill_a_mob: {
            title: "Monster Hunter",
            desc: "Kill any hostile monster",
            icon: { type: "item", name: "iron_sword", ench: false },
            type: "normal",
            criteria: [
                "minecraft:blaze",
                "minecraft:cave_spider",
                "minecraft:creeper",
                "minecraft:drowned",
                "minecraft:elder_guardian",
                "minecraft:ender_dragon",
                "minecraft:enderman",
                "minecraft:endermite",
                "minecraft:evoker",
                "minecraft:ghast",
                "minecraft:guardian",
                "minecraft:hoglin",
                "minecraft:husk",
                "minecraft:magma_cube",
                "minecraft:phantom",
                "minecraft:piglin",
                "minecraft:piglin_brute",
                "minecraft:pillager",
                "minecraft:ravager",
                "minecraft:shulker",
                "minecraft:silverfish",
                "minecraft:skeleton",
                "minecraft:slime",
                "minecraft:spider",
                "minecraft:stray",
                "minecraft:vex",
                "minecraft:vindicator",
                "minecraft:witch",
                "minecraft:wither",
                "minecraft:wither_skeleton",
                "minecraft:zoglin",
                "minecraft:zombie",
                "minecraft:zombie_villager",
                "minecraft:zombified_piglin",
            ],
        },
        trade: { title: "What a Deal!", desc: "Successfully trade with a Villager", icon: { type: "item", name: "emerald", ench: false }, type: "normal", criteria: ["traded"] },
        honey_block_slide: { title: "Sticky Situation", desc: "Jump into a Honey Block to break your fall", icon: { type: "block", name: "honey_block", ench: false }, type: "normal", criteria: ["honey_block_slide"] },
        ol_betsy: { title: "Ol' Betsy", desc: "Shoot a crossbow", icon: { type: "item", name: "crossbow_standby", ench: false }, type: "normal", criteria: ["shot_crossbow"] },
        lightning_rod_with_villager_no_fire: { title: "Surge Protector", desc: "Protect a villager from an undesired shock without starting a fire", icon: { type: "block", name: "lightning_rod", ench: false }, type: "normal", criteria: ["lightning_rod_with_villager_no_fire"] },
        fall_from_world_height: { title: "Caves & Cliffs", desc: "Free fall from the top of the world (build limit) to the bottom of the world and survive", icon: { type: "item", name: "water_bucket", ench: false }, type: "normal", criteria: ["fall_from_world_height"] },
        sleep_in_bed: { title: "Sweet Dreams", desc: "Sleep in a bed to change your respawn point", icon: { type: "item", name: "red_bed", ench: false, custom: true }, type: "normal", criteria: ["slept_in_bed"] },
        hero_of_the_village: { title: "Hero of the Village", desc: "Successfully defend a village from a raid", icon: { type: "item", name: "ominous_banner", ench: false, custom: true }, type: "challenge", criteria: ["hero_of_the_village"] },
        spyglass_at_ghast: { title: "Is It a Balloon?", desc: "Look at a ghast through a spyglass", icon: { type: "item", name: "spyglass", ench: false }, type: "normal", criteria: ["spyglass_at_ghast"] },
        throw_trident: { title: "A Throwaway Joke", desc: "Throw a trident at something.\nNote: Throwing away your only weapon is not a good idea.", icon: { type: "item", name: "trident", ench: false }, type: "normal", criteria: ["shot_trident"] },
        shoot_arrow: { title: "Take Aim", desc: "Shoot something with an arrow", icon: { type: "item", name: "bow", ench: false }, type: "normal", criteria: ["shot_arrow"] },
        kill_all_mobs: {
            title: "Monsters Hunted",
            desc: "Kill one of every hostile monster",
            icon: { type: "item", name: "diamond_sword", ench: false },
            type: "challenge",
            criteria: [
                "minecraft:blaze",
                "minecraft:cave_spider",
                "minecraft:creeper",
                "minecraft:drowned",
                "minecraft:elder_guardian",
                "minecraft:ender_dragon",
                "minecraft:enderman",
                "minecraft:endermite",
                "minecraft:evoker",
                "minecraft:ghast",
                "minecraft:guardian",
                "minecraft:hoglin",
                "minecraft:husk",
                "minecraft:magma_cube",
                "minecraft:phantom",
                "minecraft:piglin",
                "minecraft:piglin_brute",
                "minecraft:pillager",
                "minecraft:ravager",
                "minecraft:shulker",
                "minecraft:silverfish",
                "minecraft:skeleton",
                "minecraft:slime",
                "minecraft:spider",
                "minecraft:stray",
                "minecraft:vex",
                "minecraft:vindicator",
                "minecraft:witch",
                "minecraft:wither",
                "minecraft:wither_skeleton",
                "minecraft:zoglin",
                "minecraft:zombie",
                "minecraft:zombie_villager",
                "minecraft:zombified_piglin",
            ],
        },
        totem_of_undying: { title: "Postmortal", desc: "Use a Totem of Undying to cheat death", icon: { type: "item", name: "totem_of_undying", ench: false }, type: "goal", criteria: ["used_totem"] },
        summon_iron_golem: { title: "Hired Help", desc: "Summon an Iron Golem to help defend a village", icon: { type: "block", name: "carved_pumpkin", ench: false }, type: "goal", criteria: ["summoned_golem"] },
        trade_at_world_height: { title: "Star Trader", desc: "Trade with a villager at the build height limit", icon: { type: "item", name: "emerald", ench: false }, type: "normal", criteria: ["trade_at_world_height"] },
        two_birds_one_arrow: { title: "Two Birds, One Arrow", desc: "Kill two Phantoms with a piercing arrow", icon: { type: "item", name: "crossbow", ench: false }, type: "challenge", criteria: ["two_birds"] },
        whos_the_pillager_now: { title: "Who's the Pillager Now?", desc: "Give a Pillager a taste of their own medicine", icon: { type: "item", name: "crossbow", ench: false }, type: "normal", criteria: ["kill_pillager"] },
        arbalistic: { title: "Arbalistic", desc: "Kill five unique mobs with one crossbow shot", icon: { type: "item", name: "crossbow", ench: false }, type: "challenge", criteria: ["arbalistic"] },
        adventuring_time: {
            title: "Adventuring Time",
            desc: "Discover every biome",
            icon: { type: "item", name: "diamond_boots", ench: false },
            type: "challenge",
            criteria: [
                "minecraft:mushroom_fields",
                "minecraft:deep_frozen_ocean",
                "minecraft:frozen_ocean",
                "minecraft:deep_cold_ocean",
                "minecraft:cold_ocean",
                "minecraft:deep_ocean",
                "minecraft:ocean",
                "minecraft:deep_lukewarm_ocean",
                "minecraft:lukewarm_ocean",
                "minecraft:warm_ocean",
                "minecraft:stony_shore",
                "minecraft:swamp",
                "minecraft:snowy_slopes",
                "minecraft:snowy_plains",
                "minecraft:snowy_beach",
                "minecraft:windswept_gravelly_hills",
                "minecraft:grove",
                "minecraft:windswept_hills",
                "minecraft:snowy_taiga",
                "minecraft:windswept_forest",
                "minecraft:taiga",
                "minecraft:plains",
                "minecraft:meadow",
                "minecraft:beach",
                "minecraft:forest",
                "minecraft:old_growth_spruce_taiga",
                "minecraft:flower_forest",
                "minecraft:birch_forest",
                "minecraft:dark_forest",
                "minecraft:savanna_plateau",
                "minecraft:savanna",
                "minecraft:jungle",
                "minecraft:badlands",
                "minecraft:eroded_badlands",
                "minecraft:desert",
                "minecraft:wooded_badlands",
                "minecraft:jagged_peaks",
                "minecraft:stony_peaks",
                "minecraft:frozen_river",
                "minecraft:river",
                "minecraft:ice_spikes",
                "minecraft:old_growth_pine_taiga",
                "minecraft:sunflower_plains",
                "minecraft:old_growth_birch_forest",
                "minecraft:sparse_jungle",
                "minecraft:bamboo_jungle",
                "minecraft:windswept_savanna",
                "minecraft:frozen_peaks",
                "minecraft:dripstone_caves",
                "minecraft:lush_caves",
            ],
        },
        play_jukebox_in_meadows: { title: "Sound of Music", desc: "Make the Meadows come alive with the sound of music from a jukebox", icon: { type: "block", name: "jukebox", ench: false }, type: "normal", criteria: ["play_jukebox_in_meadows"] },
        walk_on_powder_snow_with_leather_boots: { title: "Light as a Rabbit", desc: "Walk on powder snow...without sinking in it", icon: { type: "item", name: "leather_boots", ench: false, custom: true }, type: "normal", criteria: ["walk_on_powder_snow_with_leather_boots"] },
        very_very_frightening: { title: "Very Very Frightening", desc: "Strike a Villager with lightning", icon: { type: "item", name: "trident", ench: false }, type: "normal", criteria: ["struck_villager"] },
        spyglass_at_dragon: { title: "Is It a Plane?", desc: "Look at the Ender Dragon through a spyglass", icon: { type: "item", name: "spyglass", ench: false }, type: "normal", criteria: ["spyglass_at_dragon"] },
        sniper_duel: { title: "Sniper Duel", desc: "Kill a Skeleton from at least 50 meters away", icon: { type: "item", name: "arrow", ench: false }, type: "challenge", criteria: ["killed_skeleton"] },
        bullseye: { title: "Bullseye", desc: "Hit the bullseye of a Target block from at least 30 meters away", icon: { type: "block", name: "target", ench: false }, type: "challenge", criteria: ["bullseye"] },
    },
    husbandry: {
        root: { title: "Husbandry", desc: "The world is full of friends and food", icon: { type: "block", name: "hay_block", ench: false }, type: "normal", criteria: ["consumed_item"] },
        safely_harvest_honey: { title: "Bee Our Guest", desc: "Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees", icon: { type: "item", name: "honey_bottle", ench: false }, type: "normal", criteria: ["safely_harvest_honey"] },
        breed_an_animal: { title: "The Parrots and the Bats", desc: "Breed two animals together", icon: { type: "item", name: "wheat", ench: false }, type: "normal", criteria: ["bred"] },
        ride_a_boat_with_a_goat: { title: "Whatever Floats Your Goat!", desc: "Get in a Boat and float with a Goat", icon: { type: "item", name: "oak_boat", ench: false }, type: "normal", criteria: ["ride_a_boat_with_a_goat"] },
        tame_an_animal: { title: "Best Friends Forever", desc: "Tame an animal", icon: { type: "item", name: "lead", ench: false }, type: "normal", criteria: ["tamed_animal"] },
        make_a_sign_glow: { title: "Glow and Behold!", desc: "Make the text of a sign glow", icon: { type: "item", name: "glow_ink_sac", ench: false }, type: "normal", criteria: ["make_a_sign_glow"] },
        fishy_business: { title: "Fishy Business", desc: "Catch a fish", icon: { type: "item", name: "fishing_rod", ench: false }, type: "normal", criteria: ["cod", "pufferfish", "salmon", "tropical_fish"] },
        silk_touch_nest: { title: "Total Beelocation", desc: "Move a Bee Nest, with 3 bees inside, using Silk Touch", icon: { type: "block", name: "bee_nest", ench: false }, type: "normal", criteria: ["silk_touch_nest"] },
        plant_seed: { title: "A Seedy Place", desc: "Plant a seed and watch it grow", icon: { type: "item", name: "wheat", ench: false }, type: "normal", criteria: ["beetroots", "melon_stem", "nether_wart", "pumpkin_stem", "wheat"] },
        wax_on: { title: "Wax On", desc: "Apply Honeycomb to a Copper block!", icon: { type: "item", name: "honeycomb", ench: false }, type: "normal", criteria: ["wax_on"] },
        bred_all_animals: {
            title: "Two by Two",
            desc: "Breed all the animals!",
            icon: { type: "item", name: "golden_carrot", ench: false },
            type: "challenge",
            criteria: [
                "minecraft:axolotl",
                "minecraft:bee",
                "minecraft:cat",
                "minecraft:chicken",
                "minecraft:cow",
                "minecraft:donkey",
                "minecraft:fox",
                "minecraft:goat",
                "minecraft:hoglin",
                "minecraft:horse",
                "minecraft:llama",
                "minecraft:mooshroom",
                "minecraft:mule",
                "minecraft:ocelot",
                "minecraft:panda",
                "minecraft:pig",
                "minecraft:rabbit",
                "minecraft:sheep",
                "minecraft:strider",
                "minecraft:turtle",
                "minecraft:wolf",
            ],
        },
        complete_catalogue: {
            title: "A Complete Catalogue",
            desc: "Tame all cat variants!",
            icon: { type: "item", name: "cod", ench: false },
            type: "challenge",
            criteria: [
                "textures/entity/cat/all_black.png",
                "textures/entity/cat/black.png",
                "textures/entity/cat/british_shorthair.png",
                "textures/entity/cat/calico.png",
                "textures/entity/cat/jellie.png",
                "textures/entity/cat/persian.png",
                "textures/entity/cat/ragdoll.png",
                "textures/entity/cat/red.png",
                "textures/entity/cat/siamese.png",
                "textures/entity/cat/tabby.png",
                "textures/entity/cat/white.png",
            ],
        },
        tactical_fishing: { title: "Tactical Fishing", desc: "Catch a fish... without a fishing rod!", icon: { type: "item", name: "pufferfish_bucket", ench: false }, type: "normal", criteria: ["cod_bucket", "pufferfish_bucket", "salmon_bucket", "tropical_fish_bucket"] },
        balanced_diet: {
            title: "A Balanced Diet",
            desc: "Eat everything that is edible, even if it's not good for you",
            icon: { type: "item", name: "apple", ench: false },
            type: "challenge",
            criteria: [
                "apple",
                "baked_potato",
                "beef",
                "beetroot",
                "beetroot_soup",
                "bread",
                "carrot",
                "chicken",
                "chorus_fruit",
                "cod",
                "cooked_beef",
                "cooked_chicken",
                "cooked_cod",
                "cooked_mutton",
                "cooked_porkchop",
                "cooked_rabbit",
                "cooked_salmon",
                "cookie",
                "dried_kelp",
                "enchanted_golden_apple",
                "glow_berries",
                "golden_apple",
                "golden_carrot",
                "honey_bottle",
                "melon_slice",
                "mushroom_stew",
                "mutton",
                "poisonous_potato",
                "porkchop",
                "potato",
                "pufferfish",
                "pumpkin_pie",
                "rabbit",
                "rabbit_stew",
                "rotten_flesh",
                "salmon",
                "spider_eye",
                "suspicious_stew",
                "sweet_berries",
                "tropical_fish",
            ],
        },
        obtain_netherite_hoe: { title: "Serious Dedication", desc: "Use a Netherite ingot to upgrade a hoe, and then reevaluate your life choices", icon: { type: "item", name: "netherite_hoe", ench: false }, type: "challenge", criteria: ["netherite_hoe"] },
        wax_off: { title: "Wax Off", desc: "Scrape Wax off of a Copper block!", icon: { type: "item", name: "stone_axe", ench: false }, type: "normal", criteria: ["wax_off"] },
        axolotl_in_a_bucket: { title: "The Cutest Predator", desc: "Catch an axolotl in a bucket", icon: { type: "item", name: "axolotl_bucket", ench: false }, type: "normal", criteria: ["axolotl_bucket"] },
        kill_axolotl_target: { title: "The Healing Power of Friendship!", desc: "Team up with an axolotl and win a fight", icon: { type: "item", name: "tropical_fish_bucket", ench: false }, type: "normal", criteria: ["kill_axolotl_target"] },
    },
};

export default advancementDetails;
