export const advancementLayouts: AdvancementLayoutType = {
    story: {
        root: { row: 4, col: 1, children: ["mine_stone"] },
        mine_stone: { row: 4, col: 3, children: ["upgrade_tools"] },
        upgrade_tools: { row: 4, col: 5, children: ["smelt_iron"] },
        smelt_iron: { row: 4, col: 7, children: ["obtain_armor", "lava_bucket", "iron_tools"] },
        obtain_armor: { row: 1, col: 9, children: ["deflect_arrow"] },
        lava_bucket: { row: 3, col: 9, children: ["form_obsidian"] },
        iron_tools: { row: 6, col: 9, children: ["mine_diamond"] },
        deflect_arrow: { row: 1, col: 11, children: [] },
        form_obsidian: { row: 3, col: 11, children: ["enter_the_nether"] },
        mine_diamond: { row: 6, col: 11, children: ["shiny_gear", "enchant_item"] },
        enter_the_nether: { row: 3, col: 13, children: ["cure_zombie_villager", "follow_ender_eye"] },
        shiny_gear: { row: 5, col: 13, children: [] },
        enchant_item: { row: 7, col: 13, children: [] },
        cure_zombie_villager: { row: 2, col: 15, children: [] },
        follow_ender_eye: { row: 4, col: 15, children: ["enter_the_end"] },
        enter_the_end: { row: 4, col: 17, children: [] },
    },
    nether: {
        root: { row: 9, col: 1, children: ["return_to_sender", "find_bastion", "obtain_ancient_debris", "fast_travel", "find_fortress", "obtain_crying_obsidian", "distract_piglin", "ride_strider"] },
        return_to_sender: { row: 1, col: 3, children: ["uneasy_alliance"] },
        find_bastion: { row: 3, col: 3, children: ["loot_bastion"] },
        obtain_ancient_debris: { row: 6, col: 3, children: ["use_lodestone", "netherite_armor"] },
        fast_travel: { row: 8, col: 3, children: [] },
        find_fortress: { row: 10, col: 3, children: ["get_wither_skull", "obtain_blaze_rod"] },
        obtain_crying_obsidian: { row: 13, col: 3, children: ["charge_respawn_anchor"] },
        distract_piglin: { row: 15, col: 3, children: [] },
        ride_strider: { row: 17, col: 3, children: ["ride_strider_in_overworld_lava", "explore_nether"] },
        uneasy_alliance: { row: 1, col: 5, children: [] },
        loot_bastion: { row: 3, col: 5, children: [] },
        use_lodestone: { row: 5, col: 5, children: [] },
        netherite_armor: { row: 7, col: 5, children: [] },
        get_wither_skull: { row: 9, col: 5, children: ["summon_wither"] },
        obtain_blaze_rod: { row: 11, col: 5, children: ["brew_potion"] },
        charge_respawn_anchor: { row: 13, col: 5, children: [] },
        ride_strider_in_overworld_lava: { row: 16, col: 5, children: [] },
        explore_nether: { row: 18, col: 5, children: [] },
        summon_wither: { row: 9, col: 7, children: ["create_beacon"] },
        brew_potion: { row: 11, col: 7, children: ["all_potions"] },
        create_beacon: { row: 9, col: 9, children: ["create_full_beacon"] },
        all_potions: { row: 11, col: 9, children: ["all_effects"] },
        create_full_beacon: { row: 9, col: 11, children: [] },
        all_effects: { row: 11, col: 11, children: [] },
    },
    end: {
        root: { row: 4, col: 1, children: ["kill_dragon"] },
        kill_dragon: { row: 4, col: 3, children: ["dragon_egg", "enter_end_gateway", "respawn_dragon", "dragon_breath"] },
        dragon_egg: { row: 1, col: 5, children: [] },
        enter_end_gateway: { row: 3, col: 5, children: ["find_end_city"] },
        respawn_dragon: { row: 5, col: 5, children: [] },
        dragon_breath: { row: 7, col: 5, children: [] },
        find_end_city: { row: 3, col: 7, children: ["elytra", "levitate"] },
        elytra: { row: 2, col: 9, children: [] },
        levitate: { row: 4, col: 9, children: [] },
    },
    adventure: {
        root: { row: 14, col: 1, children: ["voluntary_exile", "spyglass_at_parrot", "kill_a_mob", "trade", "honey_block_slide", "ol_betsy", "fall_from_world_height", "lightning_rod_with_villager_no_fire", "sleep_in_bed"] },
        voluntary_exile: { row: 1, col: 3, children: ["hero_of_the_village"] },
        spyglass_at_parrot: { row: 3, col: 3, children: ["spyglass_at_ghast"] },
        kill_a_mob: { row: 9, col: 3, children: ["throw_trident", "shoot_arrow", "kill_all_mobs", "totem_of_undying"] },
        trade: { row: 15, col: 3, children: ["summon_iron_golem", "trade_at_world_height"] },
        honey_block_slide: { row: 18, col: 3, children: [] },
        ol_betsy: { row: 20, col: 3, children: ["two_birds_one_arrow", "whos_the_pillager_now", "arbalistic"] },
        lightning_rod_with_villager_no_fire: { row: 22, col: 3, children: [] },
        fall_from_world_height: { row: 24, col: 3, children: [] },
        sleep_in_bed: { row: 26, col: 3, children: ["adventuring_time", "play_jukebox_in_meadows", "walk_on_powder_snow_with_leather_boots"] },
        hero_of_the_village: { row: 1, col: 5, children: [] },
        spyglass_at_ghast: { row: 3, col: 5, children: ["spyglass_at_dragon"] },
        throw_trident: { row: 5, col: 5, children: ["very_very_frightening"] },
        shoot_arrow: { row: 8, col: 5, children: ["sniper_duel", "bullseye"] },
        kill_all_mobs: { row: 10, col: 5, children: [] },
        totem_of_undying: { row: 12, col: 5, children: [] },
        summon_iron_golem: { row: 14, col: 5, children: [] },
        trade_at_world_height: { row: 16, col: 5, children: [] },
        two_birds_one_arrow: { row: 18, col: 5, children: [] },
        whos_the_pillager_now: { row: 20, col: 5, children: [] },
        arbalistic: { row: 22, col: 5, children: [] },
        adventuring_time: { row: 24, col: 5, children: [] },
        play_jukebox_in_meadows: { row: 26, col: 5, children: [] },
        walk_on_powder_snow_with_leather_boots: { row: 28, col: 5, children: [] },
        very_very_frightening: { row: 5, col: 7, children: [] },
        spyglass_at_dragon: { row: 3, col: 7, children: [] },
        sniper_duel: { row: 7, col: 7, children: [] },
        bullseye: { row: 9, col: 7, children: [] },
    },
    husbandry: {
        root: { row: 8, col: 1, children: ["safely_harvest_honey", "breed_an_animal", "ride_a_boat_with_a_goat", "tame_an_animal", "make_a_sign_glow", "fishy_business", "silk_touch_nest", "plant_seed"] },
        safely_harvest_honey: { row: 1, col: 3, children: ["wax_on"] },
        breed_an_animal: { row: 3, col: 3, children: ["bred_all_animals"] },
        ride_a_boat_with_a_goat: { row: 5, col: 3, children: [] },
        tame_an_animal: { row: 7, col: 3, children: ["complete_catalogue"] },
        make_a_sign_glow: { row: 9, col: 3, children: [] },
        fishy_business: { row: 11, col: 3, children: ["tactical_fishing"] },
        silk_touch_nest: { row: 13, col: 3, children: [] },
        plant_seed: { row: 15, col: 3, children: ["balanced_diet", "obtain_netherite_hoe"] },
        wax_on: { row: 1, col: 5, children: ["wax_off"] },
        bred_all_animals: { row: 3, col: 5, children: [] },
        complete_catalogue: { row: 7, col: 5, children: [] },
        tactical_fishing: { row: 11, col: 5, children: ["axolotl_in_a_bucket"] },
        balanced_diet: { row: 14, col: 5, children: [] },
        obtain_netherite_hoe: { row: 16, col: 5, children: [] },
        wax_off: { row: 1, col: 7, children: [] },
        axolotl_in_a_bucket: { row: 11, col: 7, children: ["kill_axolotl_target"] },
        kill_axolotl_target: { row: 11, col: 9, children: [] },
    },
};

export const layoutSizes = {
    story: { rows: 8, cols: 18 },
    nether: { rows: 19, cols: 12 },
    end: { rows: 8, cols: 10 },
    adventure: { rows: 29, cols: 8 },
    husbandry: { rows: 17, cols: 10 },
};
